spring:
  application:
    name: auth-server
  ldap:
   embedded:
    port : 8389
    ldif : classpath:ldap-data.ldif
    base-dn: dc=springframework,dc=org
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=UTF-8&useSSL=false
    username: root
    password: password
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 9
#  redis:
#    database: 2
#    host: localhost
#    #port: 32768
#    port: 6379
#    password: mypassword
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#    timeout: 100ms


server:
  port: 6001



management:
  endpoint:
    health:
      enabled: true




